# coding: utf-8

# flake8: noqa
from __future__ import absolute_import
# import models into model package
from swagger_server.models.get_physical_act_response_body201 import GetPhysicalActResponseBody201
from swagger_server.models.physical_act_response_body400 import PhysicalActResponseBody400
from swagger_server.models.physical_act_response_body500 import PhysicalActResponseBody500
from swagger_server.models.predict_physical_act import PredictPhysicalAct
from swagger_server.models.predict_physical_act_response_body201 import PredictPhysicalActResponseBody201
